services:
    idle.battle_manager:
        class: IdleBundle\Services\BattleManager
        arguments: ['@doctrine.orm.entity_manager', '@service_container']

    app.file_uploader:
            class: IdleBundle\Services\FileUploader
            arguments: ['%idle_images_directory%']