services:
#    idle.example:
#        class: IdleBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    idle.battle_manager:
        class: IdleBundle\Services\BattleManager
        arguments: ["@doctrine.orm.entity_manager"]