<?php

namespace IdleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BattleHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BattleHistoryRepository extends EntityRepository
{
}
