<?php

namespace IdleBundle\Repository;

use Doctrine\ORM\EntityRepository;
use IdleBundle\Entity\Characteristics;

/**
 * CharacteristicsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacteristicsRepository extends EntityRepository
{
    public function getStatsInArray(Characteristics $characteristics)
    {
        return $this->createQueryBuilder('c')
            ->where('c.id = :id')
            ->setParameter('id', $characteristics->getId())
            ->getQuery()
            ->getArrayResult();
    }
}
