<?php

namespace IdleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CraftRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CraftRepository extends EntityRepository
{
    public function getCraftsInArray($recipe)
    {
        return $this->createQueryBuilder('c')
            ->addSelect('itn')
            ->addSelect('r')
            ->innerJoin('c.itemNeeded', 'itn')
            ->innerJoin('c.recipe', 'r')
            ->where('c.recipe = :recipe')
            ->setParameter('recipe', $recipe)
            ->getQuery()
            ->getArrayResult();
    }
}
