<?php

namespace IdleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EquipmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipmentRepository extends EntityRepository
{
    public function getEquipmentTypeFromHero($hero_id, $type_id)
    {
        return $this->createQueryBuilder('e')
            ->innerJoin('e.stuff', 's')
            ->where('e.hero = :hero')
            ->setParameter('hero', $hero_id)
            ->andWhere('s.type = :type')
            ->setParameter('type', $type_id)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
