<?php

namespace IdleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HeroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeroRepository extends EntityRepository
{
    public function nbHeroHLForUser($u)
    {
        return $this->createQueryBuilder('h')
            ->select('count(h) as nb')
            ->innerJoin('h.user', 'u')
            ->where('h.user = :user')
            ->setParameter('user', $u)
            ->andWhere('h.age >= 100')
            ->getQuery()
            ->getOneOrNullResult();
    }
}
