<?php

namespace IdleBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * InventoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventoryRepository extends EntityRepository
{
    public function getStuffs(User $user)
    {
        return $this->createQueryBuilder('inv')
                    ->innerJoin('inv.item', 'i', 'WITH', 'inv.item = i.id')
                    ->innerJoin('i.typeItem', 'ti', 'WITH', 'i.typeItem = ti.id')
                    ->where('inv.user = :user')
                    ->setParameter('user', $user)
                    ->andWhere('ti.name = \'Stuff\'')
                    ->getQuery()
                    ->getResult();
    }
}
