<?php

namespace IdleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LootRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LootRepository extends EntityRepository
{
}
