<?php

namespace IdleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypeItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeItemRepository extends EntityRepository
{
}
