pick_one:
    resource: "@PickOneBundle/Controller/"
    type:     annotation
    prefix:   /pickone

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

story:
    resource: "@StoryTellBundle/Controller/"
    type:     annotation
    prefix:   /storytell

strategy:
    resource: "@StrategyBundle/Controller/"
    type:     annotation
    prefix:   /strategy

idle:
    resource: "@IdleBundle/Controller/"
    type:     annotation
    prefix:   /idle

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"