hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /connect

facebook_login:
    pattern: /login/check-facebook

google_login:
    pattern: /login/check-google

pick_one:
    resource: "@PickOneBundle/Controller/"
    type:     annotation
    prefix:   /pickone

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

story:
    resource: "@StoryTellBundle/Controller/"
    type:     annotation
    prefix:   /storytell

strategy:
    resource: "@StrategyBundle/Controller/"
    type:     annotation
    prefix:   /strategy

idle:
    resource: "@IdleBundle/Controller/"
    type:     annotation
    prefix:   /idle

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"