parameters:
    app.mailer.class:  AppBundle\Services\Mailer

services:
    app.mailer:
        class:        "%app.mailer.class%"
        arguments:    ['@doctrine.orm.entity_manager', '@mailer', '@templating']

    app.flash_message:
        class: AppBundle\EventListener\FlashMessage
        arguments: ["@session"]
        tags:
            - { name: kernel.event_listener, event: kernel.response}

#    my.oauth_aware.user_provider.service:
#        class: HWI\Bundle\OAuthBundle\Security\Core\User\FOSUBUserProvider
#        arguments:
#            - '@fos_user.user_manager'
#            - ['pass properties as array']