<?php

namespace PickOneBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FavoriteQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavoriteQuestionRepository extends EntityRepository
{
    function getFavoritesFromUser($user, $paginate = false)
    {
        $q = $this->createQueryBuilder('fq')
            ->select('q')
            ->innerJoin('PickOneBundle:Question', 'q', 'WITH', 'fq.question = q.id')
            ->where('fq.user = :user')
            ->setParameter('user', $user)
            ->getQuery();

        if ($paginate)
            return $q;

        return $q->getResult();
    }
}
