<?php

namespace PickOneBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use PickOneBundle\Entity\QuestionGenre;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{
    function getQuestionsWithGenre(QuestionGenre $genre = null, $paginate = false, $user = null)
    {
        $q = $this->createQueryBuilder('q');

        if ($user != null) {
            $sub_query = $this->getEntityManager()
                ->getRepository('PickOneBundle:UserAnswers')
                ->createQueryBuilder('ua')
                ->select('identity(ua.question)')
                ->where('ua.user = :user');

            $q->where($q->expr()->notIn('q.id', $sub_query->getDQL()))
                ->setParameter('user', $user);

            if ($genre != null) {
                $q->andWhere(':genre MEMBER OF q.genres')
                    ->setParameter('genre', $genre);
            }
        }

        if ($user == null && $genre != null) {
            $q->where(':genre MEMBER OF q.genres')
                ->setParameter('genre', $genre);
        }

        $q->getQuery();

        if ($paginate)
            return $q;

        return $q->getResult();
    }

    function getQuestionsFromAuthor($user, $paginate = false)
    {
        $q = $this->createQueryBuilder('q')
            ->where('q.author = :user')
            ->setParameter('user', $user)
            ->getQuery();

        if ($paginate)
            return $q;

        return $q->getResult();
    }
}
