<?php

namespace PickOneBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserAnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAnswersRepository extends EntityRepository
{
}
