<?php

namespace ClickerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ExperienceTableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExperienceTableRepository extends EntityRepository
{
}
