<?php

namespace StoryTellBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * ReadingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReadingsRepository extends EntityRepository
{
    function getReadingsOfUser(User $user)
    {
        return $this->createQueryBuilder('r')
            ->innerJoin('StoryTellBundle:Story', 's', 'WITH', 's.id = r.story')
            ->where('r.user = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult();
    }
}
