<?php

namespace StoryTellBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoryRepository extends EntityRepository
{
    function getReadingsOfUser($user)
    {
        return $this->createQueryBuilder('s')
            ->innerJoin('StoryTellBundle:Readings', 'r', 'WITH', 'r.story = s.id')
            ->where('r.user = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult();
    }

    function getNbChapters($story)
    {
        return $this->createQueryBuilder('s')
            ->select('count(sch) as nb_pages')
            ->innerJoin('StoryTellBundle:StoryChapter', 'sch', 'WITH', 'sch.story = s.id')
            ->where('s.id = :story')
            ->setParameter('story', $story)
            ->getQuery()
            ->getSingleScalarResult();
    }

    function getNbPages($story)
    {
        return $this->createQueryBuilder('s')
            ->select('count(sco) as nb_pages')
            ->innerJoin('StoryTellBundle:StoryChapter', 'sch', 'WITH', 'sch.story = s.id')
            ->innerJoin('StoryTellBundle:StoryContent', 'sco', 'WITH', 'sco.storyChapter = sch.id')
            ->where('s.id = :story')
            ->setParameter('story', $story)
            ->getQuery()
            ->getSingleScalarResult();
    }

    function getNextChapter($story, $chapter)
    {
        return $this->createQueryBuilder('s')
            ->select('sc')
            ->innerJoin('StoryTellBundle:StoryChapter', 'sc', 'WITH', 'sc.story = s.id')
            ->where('sc.story = :story')
            ->setParameter('story', $story)
            ->andWhere('sc.chapter = :next_chapter')
            ->setParameter('next_chapter', $chapter->getChapter() + 1)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
