<?php

namespace StoryTellBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StoryGenreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoryGenreRepository extends EntityRepository
{
}
